# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [27]:
### Assignment 1: Array Creation and Manipulation
#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
import numpy as np
import random
array1 = np.random.randint(1, 20, size=(5, 5))
print ("array1:\n", array1)
array2 = np.random.randint(1, 16, size=(4, 4))
print ("array2:\n", array2)
size = 4
def replace_diagonal(array):
    index1, index2 = 0, 0
    while index1 < size:
        array2[index1, index2] = 0
        index1 += 1
        index2 += 1
    return array2
edited_array2 = replace_diagonal(array2)
print ("edited array2:\n", edited_array2)

array1:
 [[18 11 17 15 11]
 [17 14  1  8 10]
 [ 2  5  9 19  7]
 [15 13  8  2  8]
 [10 19 14  8 17]]
array2:
 [[15  2 10  3]
 [ 6 11 13 15]
 [ 9  5  6 13]
 [ 8  1  7  2]]
edited array2:
 [[ 0  2 10  3]
 [ 6  0 13 15]
 [ 9  5  0 13]
 [ 8  1  7  0]]


In [28]:
### Assignment 2: Array Indexing and Slicing

#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
array = np.arange(1, 37).reshape(6, 6)
print("array:\n", array)
def extract_sub_array(array):
    return array[2:5, 1:4]
sub_array = extract_sub_array(array)
print("sub_array:\n", sub_array)

array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
sub_array:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


In [29]:
### Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [34]:
array1 = np.random.randint(1, 100, size=(3, 4))
array2 = np.random.randint(1, 100, size=(3, 4))
print("array1:\n", array1)
print("array2:\n", array2)
def element_wise_operations(operarion, array1, array2):
    match operation:
        case "addition":
            return array1 + array2
        case "subtraction":
            return array1 - array2
        case "multiplication":
            return array1 * array2
        case "division":
            return array1 / array2
        case _:
            return "Invalid operation"
array3 = np.arange(1, 17).reshape(4, 4)
print(array3)
def row_wise_sum(array):
    row = 0
    for row in range (4):
        print(f"row {row + 1} sum: {np.sum(array[row, :])}")
def col_wise_sum(array):
    col = 0
    for col in range (4):
        print(f"col {col + 1} sum: {np.sum(array[:, col])}")
row_wise_sum(array3)
col_wise_sum(array3)


array1:
 [[35 90  7 52]
 [45 80 55 43]
 [29 29 21 63]]
array2:
 [[38 19 16 64]
 [ 2 12 89 64]
 [50 76 17 33]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row 1 sum: 10
row 2 sum: 26
row 3 sum: 42
row 4 sum: 58
col 1 sum: 28
col 2 sum: 32
col 3 sum: 36
col 4 sum: 40


In [ ]:
import numpy as np
import random
#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
array1 = np.random.randint(1, 100, size=(5, 5))
print("array1:\n", array1)
print("mean of array1:\n", np.mean(array1))
print("median of array1:\n", np.median(array1))
print("standard deviation of array1:\n", np.std(array1))
print("variance of array1:\n", np.var(array1))
array2 = np.arange(1, 10).reshape(3, 3)
print("array2:\n", array2)
print("mean of array2:\n", np.mean(array2))
normalized_array2 = (array2 - np.mean(array2)) / np.std(array2)
print("normalized array2:\n", normalized_array2)
print("mean of normalized array2:\n", np.mean(normalized_array2))
print("standard deviation of normalized array2:\n", np.std(normalized_array2))

array1:
 [[84 75 72 37 60]
 [25 86 43 75 25]
 [74  5 18 55 96]
 [55 50 91 43 71]
 [78 88  7 94 84]]
mean of array1:
 59.64
median of array1:
 71.0
standard deviation of array1:
 27.248310039340055
variance of array1:
 742.4703999999999
array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
mean of array2:
 5.0
normalized array2:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
mean of normalized array2:
 0.0
standard deviation of normalized array2:
 1.0


In [10]:
### Assignment 5: Broadcasting

#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
import numpy as np
import random
array2d = np.random.randint(1, 10, size=(3,3))
array1d = np.random.randint(1, 10, size=(3,))
broadcasted = array1d + array2d
print("2D array:\n", array2d)
print("1D array:\n", array1d)
print("Broadcasted array:\n", broadcasted)

2D array:
 [[8 8 6]
 [8 7 3]
 [4 3 7]]
1D array:
 [9 8 7]
Broadcasted array:
 [[17 16 13]
 [17 15 10]
 [13 11 14]]


In [13]:
### Assignment 6: Linear Algebra

#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
import numpy as np
import random
array = np.random.randint(1, 10, size=(3, 3))
determinant = np.linalg.det(array)
inverse = np.linalg.inv(array)
eigenvalues = np.linalg.eig(array)
print("Array:\n", array)
print("Determinant:\n", determinant)
print("Inverse:\n", inverse)
print("Eigenvalues:\n", eigenvalues)
array1 = np.random.randint(1, 10, size=(2, 3))
array2 = np.random.randint(1, 10, size=(3, 2))
multiplication = array1 @ array2
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Multiplication:\n", multiplication)

Array:
 [[4 1 8]
 [8 3 1]
 [6 7 1]]
Determinant:
 285.99999999999994
Inverse:
 [[-0.01398601  0.19230769 -0.08041958]
 [-0.00699301 -0.15384615  0.20979021]
 [ 0.13286713 -0.07692308  0.01398601]]
Eigenvalues:
 EigResult(eigenvalues=array([13.05066779+0.j        , -2.52533389+3.94173517j,
       -2.52533389-3.94173517j]), eigenvectors=array([[ 0.59297717+0.j        , -0.44169578+0.37127419j,
        -0.44169578-0.37127419j],
       [ 0.5321196 +0.j        ,  0.6214843 +0.j        ,
         0.6214843 -0.j        ],
       [ 0.60433997+0.j        ,  0.09965795-0.52046698j,
         0.09965795+0.52046698j]]))
Array 1:
 [[3 2 9]
 [7 3 3]]
Array 2:
 [[5 6]
 [8 9]
 [1 2]]
Multiplication:
 [[40 54]
 [62 75]]


In [12]:
1+1

2